name: getx_project_structure
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  shared_preferences: ^2.2.2
  dio: ^5.3.4
  connectivity_plus: ^5.0.2
  firebase_core: ^2.24.2

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  logger: ^2.0.2+1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/

  fonts:
    - family: albert_sans
      fonts:
        - asset: assets/fonts/albertsans.ttf

